[sensor_base]
build_flags =
  -D ENV_INCLUDE_GPS=1
  -D ENV_INCLUDE_AHTX0=1
  -D ENV_INCLUDE_BME280=1
  -D ENV_INCLUDE_BMP280=1
  -D ENV_INCLUDE_SHTC3=1
  -D ENV_INCLUDE_SHT4X=1
  -D ENV_INCLUDE_LPS22HB=1
  -D ENV_INCLUDE_INA3221=1
  -D ENV_INCLUDE_INA219=1
  -D ENV_INCLUDE_INA226=1
  -D ENV_INCLUDE_INA260=1
  -D ENV_INCLUDE_MLX90614=1
  -D ENV_INCLUDE_VL53L0X=1
  -D ENV_INCLUDE_BME680=1
  -D ENV_INCLUDE_BMP085=1
lib_deps =
  adafruit/Adafruit INA3221 Library @ ^1.0.1
  adafruit/Adafruit INA219 @ ^1.2.3
  robtillaart/INA226 @ ^0.6.4
  adafruit/Adafruit INA260 Library @ ^1.5.3
  adafruit/Adafruit AHTX0 @ ^2.0.5
  adafruit/Adafruit BME280 Library @ ^2.3.0
  adafruit/Adafruit BMP280 Library @ ^2.6.8
  adafruit/Adafruit SHTC3 Library @ ^1.0.1
  sensirion/Sensirion I2C SHT4x @ ^1.1.2
  arduino-libraries/Arduino_LPS22HB @ ^1.0.2
  adafruit/Adafruit MLX90614 Library @ ^2.1.5
  adafruit/Adafruit_VL53L0X @ ^1.2.4
  stevemarple/MicroNMEA @ ^2.0.6
  adafruit/Adafruit BME680 Library @ ^2.0.4
  adafruit/Adafruit BMP085 Library @ ^1.2.4

[env:native]
platform = native
test_framework = googletest
build_flags =
  -Iinclude
  -Isrc
  -Ilib/ed25519
  -Itest/mocks
  -Itest/test_utils
  -DED25519_NO_SEED
  -I.pio/libdeps/native/Crypto/src
lib_deps =
  file://lib/ed25519
  rweather/Crypto @ ^0.4.0
test_build_src = yes
build_src_filter =
  +<Identity.cpp>
  +<Utils.cpp>